apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cicd-demo
  namespace: monitoring
  labels:
    release: kps
spec:
  selector:
    matchLabels:
      app: cicd-demo
  namespaceSelector:
    any: true
  endpoints:
  - port: http-metrics
    path: /metrics
    interval: 15s
